language: java

sudo: false

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

env:
  matrix:
    -
    - PROFILE='-P spring5'

script:
  - ./mvnw clean test-compile --no-transfer-progress
  - ./mvnw verify $PROFILE --no-transfer-progress

after_success:
  - ./mvnw coveralls:report --no-transfer-progress

notifications:
  email:
    on_failure: change
