name: Continuous Integration

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
  schedule:
  - cron: "0 6 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ['', '-P spring5']

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: m2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile
      run: ./mvnw clean test-compile --no-transfer-progress
    - name: Test
      run: ./mvnw verify ${{ matrix.profile }} --no-transfer-progress 
    - name: Coverage
      run: |
        ./mvnw coveralls:report \
        --no-transfer-progress \
        -D repoToken=${{ secrets.COVERALLS_TOKEN }} \
        -D serviceName=Github \
        -D serviceBuildUrl=https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks \
        -D branch=${{ github.head_ref || github.ref }}
