name: Java CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
  schedule:
  - cron: "0 6 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ['', '-P spring5']

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile
      run: ./mvnw clean test-compile --no-transfer-progress
    - name: Test
      run: ./mvnw verify ${{ matrix.profile }} --no-transfer-progress 
    - name: Coverage
      run: ./mvnw coveralls:report --no-transfer-progress

