name: Release Pull Request

on:
  push:
    branches:
    - release/*

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Create pull request
      uses: vsoch/pull-request-action@1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_TITLE: Release ${{ github.ref }}
        PULL_REQUEST_BODY: Bump version
